Add support of Interpolated strings. https://github.com/zzzprojects/S…
zzzprojects/System.Linq.Dynamic.Core pull request #530
Opened 2021-07-01 03:15 UTC by yangzhongke

Add support of Interpolated strings. 
see [https://github.com/zzzprojects/System.Linq.Dynamic.Core/issues/527](https://github.com/zzzprojects/System.Linq.Dynamic.Core/issues/527)

I have added two test cases: QueryableTests.FormattableString.cs and EntitiesTests.FormattableString.cs. All the tests are passed:
![image](https://user-images.githubusercontent.com/13821363/124059287-6cf8f200-da5d-11eb-8b27-c4c6d14b836d.png)

2021-07-01 09:56 UTC, StefH commented
Hello @yangzhongke, thank you for your contribution.

However, I thought that this functionality would be integrated in the current code, and not creating new extension methods.

Can you change your PR?

2021-07-02 02:03 UTC, yangzhongke commented
If there are two overloaded methods as below:
1) Where(string predicate,params object[] args)
2)Where(FormattableString predicate)

Due to the [deliberate decision by the Microsoft](https://stackoverflow.com/questions/35770713/overloaded-string-methods-with-string-interpolation) , The code Where($"Id={id}") will invoke  Where(string predicate,params object[] args) instead of Where(FormattableString predicate),  which lead to my decision to create new method names, like WhereInterpolated instead of using Where.

2021-07-02 19:38 UTC, StefH commented
Can't you just add a new method like?

Existing...
``` c#
public static IQueryable Where([NotNull] this IQueryable source, [NotNull] ParsingConfig config, [NotNull] string predicate, params object[] args)
````

New...
``` c#
public static IQueryable Where([NotNull] this IQueryable source, [NotNull] ParsingConfig config, [NotNull] FormattableString predicate)
```

2021-07-03 10:47 UTC, yangzhongke commented
I can. But where($" id={id}")  will invoke the "string predicate" version instead of "FormattableString" version. I have mentioned the reason  before.

2021-07-03 13:19 UTC, yangzhongke commented
Even EF Core created two methods to execute sql statements, ExecuteSqlRaw(string version) and ExecuteSqlInterpolated(FormatableString version). So I reckon that the two different methods solution, Where and WhereInterpolated , is a tradeoff.

2021-07-06 19:23 UTC, StefH requested changes

2021-07-08 03:09 UTC, yangzhongke commented
Agree with the renaming.
Should I do something to do the changes?

2021-07-08 08:24 UTC, StefH commented
@yangzhongke 
Yes, if possible, change your PR code.

2021-07-08 13:08 UTC, yangzhongke commented
I have renamed those two files and committed the changes.
There are two files: DynamicQueryableWithFormattableStringExtensionsand EFDynamicQueryableWithFormattableStringExtensions.
DynamicQueryableWithFormattableStringExtensions.cs contains: AllInterpolated and other XXXInterpolated methods, and EFDynamicQueryableWithFormattableStringExtensions contains: AllInterpolatedAsync and other XXXInterpolatedAsync methods.
DynamicQueryableWithFormattableStringExtensionsand .cs is already on the src/System.Linq.Dynamic.Core folder; because EFDynamicQueryableWithFormattableStringExtensions uses Microsoft.EntityFrameworkCore, just like EntityFrameworkDynamicQueryableExtensions.cs, so EFDynamicQueryableWithFormattableStringExtensions  should be on the folder Microsoft.EntityFrameworkCore.DynamicLinq.EFCore3.

2021-07-08 14:25 UTC, StefH commented on src/System.Linq.Dynamic.Core/DynamicQueryableWithFormattableStringExtensions.cs
> +        private static string ParseFormattableString(FormattableString predicate,out object[] args)
Can you do a format-file to make sure all spaces / code is aligned correctly?

2021-07-08 15:54 UTC, yangzhongke commented on src/System.Linq.Dynamic.Core/DynamicQueryableWithFormattableStringExtensions.cs
> +        private static string ParseFormattableString(FormattableString predicate,out object[] args)
Sorry, I have no idea of what you mentioned, all the indents keep consistent. Maybe you can accept this PR, and then format the codes according to your preference.

2021-07-15 04:32 UTC, yangzhongke commented on src/System.Linq.Dynamic.Core/DynamicQueryableWithFormattableStringExtensions.cs
> +        private static string ParseFormattableString(FormattableString predicate,out object[] args)
If what should I do is to format the code using the ' Format Document' functionality  in Visual Studio ,  I could do it.

2021-07-15 05:42 UTC, StefH commented on src/System.Linq.Dynamic.Core/DynamicQueryableWithFormattableStringExtensions.cs
> +        private static string ParseFormattableString(FormattableString predicate,out object[] args)
Indeed "Format Document", that's enough.

2021-07-15 06:00 UTC, yangzhongke commented on src/System.Linq.Dynamic.Core/DynamicQueryableWithFormattableStringExtensions.cs
> +        private static string ParseFormattableString(FormattableString predicate,out object[] args)
I have formatted the code and pushed. Please check.

2021-07-17 06:52 UTC, merged