fixes #580
zzzprojects/System.Linq.Dynamic.Core pull request #630
Opened 2022-09-12 08:31 UTC by jogibear9988

uses the topmost implementation of the virtual method

2022-09-12 18:54 UTC, StefH requested changes

2022-09-12 18:54 UTC, StefH commented on test/System.Linq.Dynamic.Core.Tests/Parser/MethodFinderTest.cs
> +﻿using System;
Do you need all these usings?

2022-09-12 18:54 UTC, StefH commented on src/System.Linq.Dynamic.Core/Parser/SupportedMethods/MethodFinder.cs
> +                method = ((MethodInfo)md.MethodBase).GetBaseDefinition();
question:

Is md.MethodBase always a MethodInfo?

2022-09-12 19:04 UTC, jogibear9988 commented on test/System.Linq.Dynamic.Core.Tests/Parser/MethodFinderTest.cs
> +﻿using System;
think so

2022-09-12 19:04 UTC, jogibear9988 commented on src/System.Linq.Dynamic.Core/Parser/SupportedMethods/MethodFinder.cs
> +                method = ((MethodInfo)md.MethodBase).GetBaseDefinition();
if i read here: https://docs.microsoft.com/en-us/dotnet/api/system.reflection.methodinfo.getbasedefinition?view=net-6.0

yes

2022-09-19 16:44 UTC, StefH approved these changes

2022-10-20 16:08 UTC, merged

2022-10-20 19:57 UTC, StefH commented
@jogibear9988 

I merged to master, however I noticed that some unit tests fail.

I did fix it.