Init field only on first execution
zzzprojects/System.Linq.Dynamic.Core pull request #631
Opened 2022-09-16 09:41 UTC by BBreiden

The current getter throws if called more than once, as the dictionary has already been set up.

2022-09-16 09:42 UTC, BBreiden commented
This should solve issue #629

2022-09-19 06:04 UTC, StefH requested changes
@BBreiden 

Can you please add a unit-test `DynamicClassTests.cs` which tests this fix?

2022-09-19 07:51 UTC, BBreiden commented
I've added a test. It fails without my change and works afterwards.

2022-10-16 09:00 UTC, StefH commented on src/System.Linq.Dynamic.Core/DynamicClass.cs
> +    private Dictionary<string, object?>? _propertiesDictionary = null;
why not create always an empty directory?

2022-10-16 16:17 UTC, BBreiden commented on src/System.Linq.Dynamic.Core/DynamicClass.cs
> +    private Dictionary<string, object?>? _propertiesDictionary = null;
I guess this would also work, if the getter is also changed to check that the dictionary is empty before adding the entries. One just needs to avoid double entries somehow to fix the problem. Would you like me to change the PR?

2022-10-20 06:46 UTC, BBreiden commented
Suggested change wasn't approved.

2022-10-20 13:38 UTC, StefH commented
@BBreiden 
Can you recreate your PR?

(sorry ; I did not have enough time for this project...)

2022-10-21 07:06 UTC, BBreiden commented
I reopened the PR!
:-)

2022-10-23 08:51 UTC, StefH approved these changes

2022-10-23 08:52 UTC, merged