Handle UseParameterizedNamesInDynamicQuery when parsing dynamic OfType function
zzzprojects/System.Linq.Dynamic.Core pull request #723
Opened 2023-07-11 11:42 UTC by yonguelink

Fixes #722

2023-07-11 18:11 UTC, StefH requested changes

2023-07-11 18:11 UTC, StefH commented on src/System.Linq.Dynamic.Core/Parser/ExpressionParser.cs
> +                _expressionHelper.TryUnwrapAsConstantExpression(memberExpression, out var unwrappedConstantExpression);
The TryUnwrapAsConstantExpression returns a bool indicating it's valid.

This code does not check it ?

2023-07-11 18:35 UTC, yonguelink commented on src/System.Linq.Dynamic.Core/Parser/ExpressionParser.cs
> +                _expressionHelper.TryUnwrapAsConstantExpression(memberExpression, out var unwrappedConstantExpression);
I started working with that if, but I would've either needed to duplicate the `throw ParseError` from below OR remove the `default` case from the `switch` & throw there.

I decided to ignore the boolean to make things straightforward, letting the `ResolveTypeFromExpressionValue` handle the potential null `unwrappedConstantExpression` out var (line 2025)

If you prefer the approach with the bool check, I can do that, but which one would you prefer?

- Dropping the `default` case from the `switch` to avoid duplicating the `throw` statement
- Duplicating the `throw` statement in the `MemberExpression` case of the switch

2023-07-11 18:49 UTC, yonguelink commented on src/System.Linq.Dynamic.Core/Parser/ExpressionParser.cs
> +                _expressionHelper.TryUnwrapAsConstantExpression(memberExpression, out var unwrappedConstantExpression);
I went with the first option to drop the `default` case while checking for the `TryUnwrapAsConstantExpression` return value instead of propagating potential null/default values.

That makes more sense to me.

2023-07-11 18:57 UTC, StefH approved these changes

2023-07-13 11:11 UTC, yonguelink commented
@StefH is there something else to do to get this completed?

2023-07-15 09:20 UTC, StefH commented
@yonguelink 
It's good. Thank you.

I'll merge this to master.

2023-07-15 09:20 UTC, merged