added symbol check when checking for identifier
zzzprojects/System.Linq.Dynamic.Core pull request #728
Opened 2023-08-02 14:28 UTC by abbasc52

Fixes #727

2023-08-06 12:07 UTC, StefH requested changes

2023-08-06 12:07 UTC, StefH commented on src/System.Linq.Dynamic.Core/Parser/ExpressionParser.cs
>          var extraCondition = !_parsingConfig.PrioritizePropertyOrFieldOverTheType ||
This code gets complex to understand.

Change it to:
```
var isValueAType = value is Type;

var hasPropertyOrField = _it != null && FindPropertyOrField(_it.Type, _textParser.CurrentToken.Text, false) != null;

var hasSymbol = _symbols.ContainsKey(_textParser.CurrentToken.Text);

var shouldNotPrioritizePropertyOrFieldOverTheType = !_parsingConfig.PrioritizePropertyOrFieldOverTheType;
var shouldPrioritizeAndNoMatch = _parsingConfig.PrioritizePropertyOrFieldOverTheType && !(isValueAType && (hasPropertyOrField || hasSymbol));

var extraCondition = shouldNotPrioritizePropertyOrFieldOverTheType || shouldPrioritizeAndNoMatch;
```

2023-08-09 16:46 UTC, StefH commented
@abbasc52 
Can you take a look at my comment?

2023-08-09 16:48 UTC, abbasc52 commented
Hi @StefH , sure i was busy last week, will try adding it tomorrow

2023-08-10 09:11 UTC, abbasc52 commented on src/System.Linq.Dynamic.Core/Parser/ExpressionParser.cs
>          var extraCondition = !_parsingConfig.PrioritizePropertyOrFieldOverTheType ||
@StefH updated the PR with your suggestion with slight changes to ensure performance is not impacted. Please have a look

2023-08-11 15:42 UTC, abbasc52 commented
@StefH Can you check if anything else is required?

2023-08-13 18:39 UTC, StefH approved these changes

2023-08-13 18:40 UTC, merged