Applied case sensitivity settings to KeywordHelper
zzzprojects/System.Linq.Dynamic.Core pull request #735
Opened 2023-08-15 14:33 UTC by abbasc52

Extended case sensitivity settings to KeywordHelper

2023-08-15 14:36 UTC, abbasc52 commented
@StefH, I am unable to find the right place to add test cases for this, could you guide me?

2023-08-16 15:58 UTC, StefH commented
@abbasc52 
1. Changing this could break some existing usage. So in case this functionality is added, a new setting `KeywordsAreCaseSensitive` is needed.

2. Add a new test here `\Parser\KeywordsHelperTests`

2023-08-27 15:04 UTC, abbasc52 commented
@StefH Addressed your comment and added test cases, please review again

2023-10-21 12:33 UTC, abbasc52 commented
@StefH when can we merge/release this PR?

2023-10-21 15:19 UTC, StefH commented
> @StefH when can we merge/release this PR?

I'll take a look.

2023-10-29 08:31 UTC, StefH commented
because of PR https://github.com/zzzprojects/System.Linq.Dynamic.Core/pull/755, this PR needs to be updated....

2023-11-25 10:26 UTC, abbasc52 commented
@StefH I have updated the PR. Although looking at your PR, you seem to have fixed case issue with custom types. This PR will only help people make Context keywords case sensitive via config . I will leave it to you if you want to complete this PR.

2023-11-25 10:27 UTC, abbasc52 commented
My original goal of this PR was to make predefined and custom types case sensitive :)

2023-11-26 10:22 UTC, StefH requested changes

2023-11-26 10:22 UTC, StefH commented on src/System.Linq.Dynamic.Core/Parser/KeywordsHelper.cs
> +        _keywordMapping = new(config is { AreKeywordsCaseSensitive: true } ? StringComparer.Ordinal : StringComparer.OrdinalIgnoreCase)
Just use `config.AreKeywordsCaseSensitive`

2023-11-26 10:22 UTC, StefH commented on test/System.Linq.Dynamic.Core.Tests/Parser/KeywordsHelperTests.cs
> +    }
add newline

2023-11-26 10:22 UTC, StefH commented on test/System.Linq.Dynamic.Core.Tests/Parser/KeywordsHelperTests.cs
> +
no newline

2023-11-26 10:22 UTC, StefH commented on test/System.Linq.Dynamic.Core.Tests/Parser/KeywordsHelperTests.cs
> +
no newline

2023-11-26 10:22 UTC, StefH commented on test/System.Linq.Dynamic.Core.Tests/Parser/KeywordsHelperTests.cs
> +            var result = keywordsHelper.TryGetValue(
use 1 line

2023-11-26 10:22 UTC, StefH commented on test/System.Linq.Dynamic.Core.Tests/Parser/KeywordsHelperTests.cs
> +        [Theory]
just create 1 unit test which tests all keywords + context-keywords and combine case-sensitive and case-insensitive:


``` c#
[Theory]
[InlineData("it", true, true)]
[InlineData("it", false, true)]
[InlineData("IT", true, false)]
[InlineData("IT", false, true)]
// and more
public void TryGetValue(string name, bool areKeywordsCaseSensitive, bool expected)
{
  // Arrange
  var config = new ParsingConfig
  {
    AreKeywordsCaseSensitive = areKeywordsCaseSensitive
  };
  var keywordsHelper = this.CreateKeywordsHelper(config);

  // Act
  var result = keywordsHelper.TryGetValue(name, out _);

  // Assert 
  result.Should().Be(expected);
}
```

2023-11-28 16:18 UTC, StefH commented
@abbasc52 
See my review comments.

2024-01-13 08:24 UTC, abbasc52 commented
@StefH fixed the review comments

2024-01-13 10:42 UTC, StefH requested changes

2024-01-13 10:42 UTC, StefH commented on test/System.Linq.Dynamic.Core.Tests/Parser/KeywordsHelperTests.cs
> +            var keywordsHelper = this.CreateKeywordsHelper(new ParsingConfig { AreKeywordsCaseSensitive = areKeywordsCaseSensitive });
`this` i not needed

2024-01-13 10:42 UTC, StefH commented on test/System.Linq.Dynamic.Core.Tests/Parser/KeywordsHelperTests.cs
> +        public void TryGetValue_WithCaseSensitiveSettings_ReturnsResultAsExpected(string name, bool areKeywordsCaseSensitive,bool expected)
Do a format file to align the source code (adding some spaces)

2024-01-23 12:10 UTC, StefH commented
@abbasc52
See my review comments.

2024-02-07 07:34 UTC, StefH commented
@abbasc52
See my review comments.

2024-02-29 08:38 UTC, StefH commented
Hello @abbasc52, can you please take a look at my review comments?

2024-04-06 19:23 UTC, StefH commented
Hello @abbasc52, can you please take a look at my review comments?

2024-05-28 20:11 UTC, StefH commented
Hello @abbasc52, can you please take a look at my review comments?

2024-12-07 07:33 UTC, closed without merging